apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadtvis5102-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadtvis5102-tenant-component
    app.kubernetes.io/part-of: loadtvis5102-tenant-app
  name: loadtvis5102-tenant-component
  namespace: loadtvis5102-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadtvis5102-tenant-component
    weight: null
status: {}
